import '../models/product.dart';
import '../models/category.dart';
import '../models/brand.dart';
import '../models/banner.dart';

class MockData {
  static List<HomeBanner> banners = [
    HomeBanner(
      id: '1',
      imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
      title: 'Shine',
      subtitle: 'اشراقة تبدأ من هنا',
    ),
    HomeBanner(
      id: '2',
      imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800',
      title: 'عناية فائقة',
      subtitle: 'للبشرة والجسم والشعر',
    ),
    HomeBanner(
      id: '3',
      imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
      title: 'منتجات طبيعية',
      subtitle: 'نتائج مذهلة',
    ),
  ];

  static List<Category> categories = [
    Category(
      id: 'skincare',
      nameAr: 'العناية بالبشرة',
      nameEn: 'Skin Care',
      iconUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=200',
    ),
    Category(
      id: 'bodycare',
      nameAr: 'العناية بالجسم',
      nameEn: 'Body Care',
      iconUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=200',
    ),
    Category(
      id: 'haircare',
      nameAr: 'العناية بالشعر',
      nameEn: 'Hair Care',
      iconUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=200',
    ),
    Category(
      id: 'suncare',
      nameAr: 'الحماية من الشمس',
      nameEn: 'Sun Care',
      iconUrl: 'https://images.unsplash.com/photo-1556227703-a5a4d87f0726?w=200',
    ),
    Category(
      id: 'makeup',
      nameAr: 'المكياج',
      nameEn: 'Makeup',
      iconUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=200',
    ),
    Category(
      id: 'fragrance',
      nameAr: 'العطور',
      nameEn: 'Fragrance',
      iconUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=200',
    ),
  ];

  static List<Brand> brands = [
    Brand(id: 'axisy', name: 'AXIS-Y', logoUrl: 'https://via.placeholder.com/150x60?text=AXIS-Y'),
    Brand(id: 'anua', name: 'Anua', logoUrl: 'https://via.placeholder.com/150x60?text=Anua'),
    Brand(id: 'biorepair', name: 'Biorepair', logoUrl: 'https://via.placeholder.com/150x60?text=Biorepair'),
    Brand(id: 'biobalance', name: 'BioBalance', logoUrl: 'https://via.placeholder.com/150x60?text=BioBalance'),
    Brand(id: 'biooil', name: 'Bio-Oil', logoUrl: 'https://via.placeholder.com/150x60?text=Bio-Oil'),
    Brand(id: 'cosmo', name: 'COSMO', logoUrl: 'https://via.placeholder.com/150x60?text=COSMO'),
    Brand(id: 'derma', name: 'Derma Pella', logoUrl: 'https://via.placeholder.com/150x60?text=Derma+Pella'),
    Brand(id: 'cosrx', name: 'COSRX', logoUrl: 'https://via.placeholder.com/150x60?text=COSRX'),
    Brand(id: 'purest', name: 'The Purest Solutions', logoUrl: 'https://via.placeholder.com/150x60?text=Purest'),
    Brand(id: 'keshking', name: 'Kesh King', logoUrl: 'https://via.placeholder.com/150x60?text=Kesh+King'),
  ];

  static List<Product> products = [
    Product(
      id: '1',
      nameAr: 'سيروم فيتامين سي للإشراق',
      nameEn: 'Vitamin C Brightening Serum',
      brandId: 'purest',
      categoryId: 'skincare',
      descriptionAr: 'سيروم فيتامين سي المركز للحصول على بشرة مشرقة ونضرة. يحتوي على 15% فيتامين سي نقي يعمل على توحيد لون البشرة ومحاربة علامات التقدم في السن. مناسب لجميع أنواع البشرة.',
      descriptionEn: 'Concentrated Vitamin C serum for radiant and fresh skin. Contains 15% pure Vitamin C that works to even out skin tone and fight signs of aging.',
      price: 25.000,
      oldPrice: null,
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
      tags: ['مشرق', 'مضاد للتجاعيد'],
      skinTypes: ['جميع أنواع البشرة'],
      concerns: ['تصبغات', 'بهتان'],
      usage: 'يستخدم صباحاً قبل المرطب وواقي الشمس',
      ingredients: 'Vitamin C 15%, Hyaluronic Acid, Vitamin E, Ferulic Acid',
    ),
    Product(
      id: '2',
      nameAr: 'كريم الحماية من الشمس SPF50+',
      nameEn: 'SPF50+ Blemish Defense Cream',
      brandId: 'purest',
      categoryId: 'suncare',
      descriptionAr: 'كريم واقي من الشمس بعامل حماية 50+ مع خصائص مضادة للشوائب. يحمي البشرة من أشعة UVA و UVB مع ترطيب مثالي طوال اليوم. لا يترك أثراً أبيض.',
      descriptionEn: 'Sunscreen cream with SPF50+ protection and anti-blemish properties.',
      price: 24.000,
      oldPrice: 28.000,
      images: ['https://images.unsplash.com/photo-1556227703-a5a4d87f0726?w=400'],
      tags: ['واقي شمس', 'ترطيب'],
      skinTypes: ['جميع أنواع البشرة', 'البشرة الحساسة'],
      concerns: ['حماية من الشمس', 'ترطيب'],
      usage: 'يطبق كل صباح كخطوة أخيرة في روتين العناية',
      ingredients: 'Zinc Oxide, Titanium Dioxide, Niacinamide, Centella Asiatica',
    ),
    Product(
      id: '3',
      nameAr: 'شامبو ضد تساقط الشعر',
      nameEn: 'Anti Hair Fall Shampoo',
      brandId: 'keshking',
      categoryId: 'haircare',
      descriptionAr: 'شامبو طبيعي مستخلص من الأعشاب الهندية الأصيلة. يقوي بصيلات الشعر ويمنع التساقط. غني بزيت الأملا والبراهمي.',
      descriptionEn: 'Natural shampoo extracted from authentic Indian herbs.',
      price: 6.500,
      oldPrice: null,
      images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400'],
      tags: ['طبيعي', 'ضد التساقط'],
      skinTypes: ['جميع أنواع الشعر'],
      concerns: ['تساقط الشعر', 'ضعف الشعر'],
      usage: 'يستخدم 2-3 مرات أسبوعياً مع التدليك لمدة 2-3 دقائق',
      ingredients: 'Amla Oil, Brahmi Extract, Bhringraj, Neem',
    ),
    Product(
      id: '4',
      nameAr: 'غسول الوجه للبشرة الدهنية',
      nameEn: 'Oil Control Facial Cleanser',
      brandId: 'cosrx',
      categoryId: 'skincare',
      descriptionAr: 'غسول رغوي لطيف للبشرة الدهنية والمختلطة. يزيل الزيوت الزائدة والشوائب دون جفاف البشرة. يحتوي على حمض الساليسيليك لمحاربة حب الشباب.',
      descriptionEn: 'Gentle foaming cleanser for oily and combination skin.',
      price: 12.000,
      oldPrice: 15.000,
      images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400'],
      tags: ['للبشرة الدهنية', 'ضد حب الشباب'],
      skinTypes: ['البشرة الدهنية', 'البشرة المختلطة'],
      concerns: ['حب الشباب', 'الزيوت الزائدة', 'المسام الواسعة'],
      usage: 'يستخدم صباحاً ومساءً على بشرة مبللة',
      ingredients: 'Salicylic Acid 0.5%, Tea Tree Oil, Aloe Vera, Centella Asiatica',
    ),
    Product(
      id: '5',
      nameAr: 'تونر حمض الهيالورونيك',
      nameEn: 'Hyaluronic Acid Toner',
      brandId: 'anua',
      categoryId: 'skincare',
      descriptionAr: 'تونر مرطب بحمض الهيالورونيك متعدد الأوزان الجزيئية. يعمل على ترطيب البشرة بعمق وتحضيرها لاستقبال المنتجات التالية.',
      descriptionEn: 'Hydrating toner with multi-molecular weight hyaluronic acid.',
      price: 18.000,
      oldPrice: null,
      images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400'],
      tags: ['ترطيب عميق', 'حمض الهيالورونيك'],
      skinTypes: ['جميع أنواع البشرة', 'البشرة الجافة'],
      concerns: ['جفاف', 'خطوط دقيقة'],
      usage: 'يستخدم بعد الغسول صباحاً ومساءً',
      ingredients: 'Hyaluronic Acid (3 types), Beta-Glucan, Panthenol',
    ),
    Product(
      id: '6',
      nameAr: 'زيت البشرة المتخصص',
      nameEn: 'Specialist Skincare Oil',
      brandId: 'biooil',
      categoryId: 'bodycare',
      descriptionAr: 'زيت متخصص للعناية بالندبات وعلامات التمدد وتفاوت لون البشرة. تركيبة فريدة مع PurCellin Oil لامتصاص سريع.',
      descriptionEn: 'Specialist oil for scars, stretch marks and uneven skin tone.',
      price: 22.000,
      oldPrice: 26.000,
      images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400'],
      tags: ['علامات التمدد', 'الندبات'],
      skinTypes: ['جميع أنواع البشرة'],
      concerns: ['ندبات', 'علامات التمدد', 'تفاوت اللون'],
      usage: 'يدلك على المنطقة المطلوبة بحركات دائرية مرتين يومياً',
      ingredients: 'PurCellin Oil, Vitamin A, Vitamin E, Calendula Oil, Lavender Oil',
    ),
    Product(
      id: '7',
      nameAr: 'مرطب الوجه اليومي',
      nameEn: 'Daily Face Moisturizer',
      brandId: 'biobalance',
      categoryId: 'skincare',
      descriptionAr: 'مرطب يومي خفيف سريع الامتصاص. يوفر ترطيباً مكثفاً لمدة 24 ساعة مع حماية من العوامل البيئية.',
      descriptionEn: 'Lightweight daily moisturizer with 24-hour hydration.',
      price: 14.000,
      oldPrice: null,
      images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400'],
      tags: ['ترطيب', 'يومي'],
      skinTypes: ['جميع أنواع البشرة'],
      concerns: ['جفاف', 'حماية'],
      usage: 'يستخدم صباحاً ومساءً بعد السيروم',
      ingredients: 'Ceramides, Squalane, Shea Butter, Vitamin E',
    ),
    Product(
      id: '8',
      nameAr: 'سيروم العين مضاد للتجاعيد',
      nameEn: 'Radiance Eye Contour Serum',
      brandId: 'purest',
      categoryId: 'skincare',
      descriptionAr: 'سيروم مركز لمنطقة العين يعالج الهالات السوداء والانتفاخات والخطوط الدقيقة. تركيبة خفيفة سريعة الامتصاص.',
      descriptionEn: 'Concentrated eye serum for dark circles, puffiness and fine lines.',
      price: 25.000,
      oldPrice: 30.000,
      images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=400'],
      tags: ['منطقة العين', 'مضاد للتجاعيد'],
      skinTypes: ['جميع أنواع البشرة'],
      concerns: ['هالات سوداء', 'انتفاخ', 'تجاعيد العين'],
      usage: 'يستخدم صباحاً ومساءً بالتربيت الخفيف حول العين',
      ingredients: 'Caffeine, Peptides, Vitamin K, Hyaluronic Acid',
    ),
    Product(
      id: '9',
      nameAr: 'ماسك الطين للبشرة الدهنية',
      nameEn: 'Deep Cleansing Clay Mask',
      brandId: 'axisy',
      categoryId: 'skincare',
      descriptionAr: 'ماسك طين منقي للبشرة الدهنية والمعرضة لحب الشباب. ينظف المسام بعمق ويتحكم في الزيوت الزائدة.',
      descriptionEn: 'Purifying clay mask for oily and acne-prone skin.',
      price: 16.000,
      oldPrice: null,
      images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400'],
      tags: ['ماسك', 'تنظيف عميق'],
      skinTypes: ['البشرة الدهنية', 'البشرة المختلطة'],
      concerns: ['مسام واسعة', 'زيوت زائدة', 'حب الشباب'],
      usage: 'يستخدم 1-2 مرة أسبوعياً لمدة 10-15 دقيقة',
      ingredients: 'Kaolin Clay, Bentonite, Tea Tree Oil, Witch Hazel',
    ),
    Product(
      id: '10',
      nameAr: 'كريم الليل المجدد',
      nameEn: 'Renewal Night Cream',
      brandId: 'derma',
      categoryId: 'skincare',
      descriptionAr: 'كريم ليلي غني يعمل على تجديد البشرة أثناء النوم. يحتوي على الريتينول ومضادات الأكسدة لمحاربة علامات التقدم في السن.',
      descriptionEn: 'Rich night cream for skin renewal while you sleep.',
      price: 28.000,
      oldPrice: 35.000,
      images: ['https://images.unsplash.com/photo-1570194065650-d99fb4ee8e2e?w=400'],
      tags: ['ليلي', 'مضاد للتجاعيد'],
      skinTypes: ['جميع أنواع البشرة', 'البشرة الناضجة'],
      concerns: ['تجاعيد', 'ترهل', 'بهتان'],
      usage: 'يستخدم مساءً كخطوة أخيرة في الروتين',
      ingredients: 'Retinol 0.3%, Peptides, Vitamin E, Jojoba Oil',
    ),
  ];

  static List<Product> get bestSellers => products.take(4).toList();
}
