// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtR4k0hBGuOUj8ERt7xBCrFPTgtvRZnF4',
    appId: '1:480478282778:web:85ad8a7fe15ac21850fda3',
    messagingSenderId: '480478282778',
    projectId: 'shine-app-b02ef',
    authDomain: 'shine-app-b02ef.firebaseapp.com',
    storageBucket: 'shine-app-b02ef.firebasestorage.app',
    measurementId: 'G-8KGQLQM8YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJ5IHqzBKHmGrIoimnvyfQBREl1leDUc',
    appId: '1:480478282778:android:a54a328ce80bff6d50fda3',
    messagingSenderId: '480478282778',
    projectId: 'shine-app-b02ef',
    storageBucket: 'shine-app-b02ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrpxMz511-JQJ_-yk8onxtXqTqR7ALVfg',
    appId: '1:480478282778:ios:ca87acb7f956783050fda3',
    messagingSenderId: '480478282778',
    projectId: 'shine-app-b02ef',
    storageBucket: 'shine-app-b02ef.firebasestorage.app',
    iosBundleId: 'com.shinepara.shineparaApp',
  );

}